### PR TITLE
Fixed xinput naming conventions

### PR DESCRIPTION
**Pull request by light2yellow**
For me only this variant works, because it appears to be named in such manner in xinput. Before this mouse axes inversion didn't work.

### CODE REVIEW

**Comment by Light2Yellow** [comment]
I just saw the repo owner has made a commit to add "Mouse". Strange or not, I use "unpatched" 4.1.11-ck kernel under Arch Linux. My `xinput` output:

    ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Surface Type Cover            	id=7	[slave  pointer  (2)]
    ⎜   ↳ NTRG0001:01 1B96:1B05 Pen               	id=8	[slave  pointer  (2)]
    ⎜   ↳ NTRG0001:01 1B96:1B05                   	id=9	[slave  pointer  (2)]
    ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
        ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
        ↳ Video Bus                               	id=6	[slave  keyboard (3)]

**Comment by danielquinn** [comment]
Weird.  This is the output of xinput on my Gentoo box (4.2.3-gentoo):

    $ xinput 
    ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Surface Type Cover Consumer Control	id=8	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Surface Type Cover UNKNOWN    	id=9	[slave  pointer  (2)]
    ⎜   ↳ Microsoft Surface Type Cover Mouse      	id=11	[slave  pointer  (2)]
    ⎜   ↳ NTRG0001:01 1B96:1B05 Pen               	id=14	[slave  pointer  (2)]
    ⎜   ↳ NTRG0001:01 1B96:1B05                   	id=15	[slave  pointer  (2)]
    ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
        ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
        ↳ Video Bus                               	id=6	[slave  keyboard (3)]
        ↳ EC                                      	id=7	[slave  keyboard (3)]
        ↳ Microsoft Surface Type Cover Keyboard   	id=10	[slave  keyboard (3)]
        ↳ Microsoft LifeCam Front                 	id=12	[slave  keyboard (3)]
        ↳ Microsoft LifeCam Rear                  	id=13	[slave  keyboard (3)]

Isn't there a better way to refer to these components if the name changes from platform to platform?

**Comment by Light2Yellow** [comment]
Someone capable could write a search script and make it to work depending on the string returned, but as for now I think a note in comments or Readme should be left to make this script work for particular distribution (and encourage other hosts to test it).

**Comment by light2yellow** [comment]
I've compiled an Arch Linux kernel with SP3 patches from Github and got _almost_ the same results as you (maybe this is because of different patch sources or differences in kernel options):
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ A4TECH USB Device                       	id=8	[slave  pointer  (2)]
⎜   ↳ A4TECH USB Device                       	id=9	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Mouse      	id=11	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover Consumer Control	id=12	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Type Cover UNKNOWN    	id=13	[slave  pointer  (2)]
⎜   ↳ NTRG0001:01 1B96:1B05 Pen               	id=16	[slave  pointer  (2)]
⎜   ↳ NTRG0001:01 1B96:1B05                   	id=17	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Surface Pro 3 Buttons                   	id=7	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover Keyboard   	id=10	[slave  keyboard (3)]
    ↳ Microsoft LifeCam Front                 	id=14	[slave  keyboard (3)]
    ↳ Microsoft LifeCam Rear                  	id=15	[slave  keyboard (3)]
    ↳ A4TECH USB Device                       	id=18	[slave  keyboard (3)]
    ↳ Microsoft Surface Type Cover Consumer Control	id=19	[slave  keyboard (3)]

```
I think the issue may be closed.

**Pull request closed without merging**
