### PR TITLE
Updates for kernel 4.1.0 and notes

### PR DESCRIPTION
**Pull request by cydergoth**
This is the second version of this patchset to bump to 4.1.0-r1 and fix the touchscreen.

Note: there are still some redundant entries in the .config file which will need to be cleaned up, around touchscreen and other device which the surface doesn't support.

### CODE REVIEW

**Comment by cydergoth** [comment]
Note: The pen is a bit odd. It has a BT LE function, but that is only for the blue button on the end. The actual touch function and mouse buttons are driven by the touchscreen and don't need Bluetooth. That button sends a short connect/disconnect burst when pressed, which if BT is correctly configured will cause a DBus event. I'm currently experimenting with code to handle that, probably to do something useful in Awesome WM. 

For virtual keyboard, I'm using XvKbd, which works very well and with a few tweaks to the Awesome-wm config will be very usable.

I also have a slightly updated .config with the correct kernel settings to use Docker.

**Comment by cydergoth** [comment]
If you have Awesome WM, add this to your rc.lua and you will have notifications on the Blue button being pressed. (If you're not using Awesome WM with Surface Gentoo, you should give it a try!)

Note: Replace my pen BT ID with yours in the snippet below
Note: use Bluez 5.32 or higher. 
Note: If not working, use *# hciconfig hci0 up* and then use bluetoothctl to pair the pen. When you do this the pen will connect and disconnect immediately, this is normal as it uses connect as a way to signal a press.
Note: Bluetooth seems to not resume by default, working on that. For now run *# hciconfig hci0 up* again

-- Register a DBus handler for Surface Pro 3 Pen events
function surface_pen_blue_btn(...)
   local data= { ... }
   naughty.notify({ text="" .. data[1]["path"] } )
   naughty.notify({ text="" .. data[2] } )
   if data[3]["Connected"] then
      naughty.notify({ text="True" } )
   else
      naughty.notify({ text="True" } )
   end
   return
end

dbus.request_name("system","org.freedesktop.DBus.Properties")
dbus.add_match("system","interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/bluez/hci0/dev_C9_31_04_31_36_DD'")
dbus.connect_signal("org.freedesktop.DBus.Properties",surface_pen_blue_btn)
naughty.notify({ text="Registered DBus Handler for Surface Pro 3 pen" })

**Comment by cydergoth** [comment]
I have tracked down the issue with the Pen buttons. In the XF86 file evdev.c there is a hardcoded mapping table which does not contain the a mapping for the BTN_TOOL_* codes the pen sends. There are two possible fixes. One is to add a section hardcoding the mapping in the same way as the existing one, the other is to use an existing patch which adds a soft, user defined mapping table. 

I have yet to decide which is the preferred solution.

**Comment by danielquinn** [comment]
Well I'm not sure what value there is in allowing for a user-defined table.  I mean, how likely is someone going to want to change that?  My vote is for a hard one.

**Comment by cydergoth** [comment]
The hardcoded mapping looks like the simplest, most direct and in keeping with the existing code, however I loathe hardcoding, I'd probably bind a lua interpreter in there. LOL. 

This is the URL of the existing patch : http://www.thenautilus.net/SW/xf86-input-evdev/

**Comment by cydergoth** [comment]
Related bug: https://bugs.freedesktop.org/show_bug.cgi?id=11227

**Comment by cydergoth** [comment]
Note: if you're not using Awesome WM, dbus-monitor can be used to detect the Pen Blue button events and trigger behavior, or your other WM may have appropriate DBus integration.

**Comment by cydergoth** [comment]
Added hardcoded patch to fix the top stylus button on the Surface Pro 3 Stylus

This is an initial attempt at a patch and contains debug code, it also may not be correct.

**Comment by cydergoth** [comment]
Looks like the Yoga Pro lot have figured out sensor hub, I'll see what we can leverage from them

https://github.com/pfps/yoga-laptop

**Comment by cydergoth** [comment]
Surface Pro 3 gyro and inclinometer are on the /sys/bus/iio/devices/* tree (iio is a new one on me!) and they both will respond to single value reads after enabling the channels and polling the "raw" single value character devices. It does, however, seem as if the buffered device only works after a number of raw character device reads, suggesting that triggering is not working properly. This probably means the iio trigger subsystem is not correctly configured

**Comment by cydergoth** [comment]
Daniel, should I leave this pull request pending or close it?

**Comment by danielquinn** [comment]
Appologies. You caught me at a bad time with all of these suggestions.  I was out of the country from the 7th until only a few days ago so I haven't had time to take a whack at this.  I've got some time this weekend, so I'll be giving your patches a try.

One quick question though: I see you're opting to remove the existing entries in `hid-core.c` and are adding what appears to be new TypeCover support in `hid-microsoft.c`.  Is this because you see that this is how things are shaping up in newer kernels, or is this way of doing things just better?

Also note that I'm in the Netherlands, so turn-around times might be longer than you're used to if you're not in Europe.

**Comment by cydergoth** [comment]
That change was made based on the changes in the kernel, and some other patches for the Surface. It seems to work on this device, and I believe it is the way forward, but I could be wrong

**Comment by danielquinn** [comment]
Cool beans.  I'm testing it on my environment now and will post back when I have things booted and working under 4.1.2 (I've been using 3.19.3 for the longest time)

**Comment by cydergoth** [comment]
I think I might have br0ken touchscreen in the latest 4.1.2 patch

**Comment by danielquinn** [comment]
Truth be told, touchscreen has always been a bit shaky for me, regardless of which kernel I'm running.  If you have other suggested changes though, I'm happy to test them out.

**Comment by cydergoth** [comment]
It's possible I broke my X11 configuration whilst messing with the pen. The good thing is the pen seems to work better, and I mostly use that not touch anyway

**Comment by danielquinn** [comment]
Ok it's all merged!  I've done the compile and test on my SP3 and everything is perfect.  I'm using it right now in fact.

I went the manual route to merge because I had to change a few things:

* The `config` file you had in there was just way too different from the others.  There was no way to see what was added and for what purpose so I opted to go the route of using `make oldconfig` on the new sources after applying your kernel patch.
* There were a lot of bits that you added to the README files that needed some reformatting.  While I appreciate all of the additions, please try to keep them as separate branches (and therefore pull requests) so it makes the merge process less arduous.
* I noted that you've got a new `x11` directory added there, but did not include it in the main README as part of the install.  I haven't tried this myself yet, but when I do, and if it works alright (you mentioned that it might be the cause of your touchscreen problems) I'll add it to the main install instructions.
    * This might be better however as a separate overlay or something.  The instructions you have there appear to depend on the user doing a manual install every time they need to install/update evdev, which could lead to people doing an `emerge --sync` and watching their evdev behaviour revert.
* And of course I gave you credit both in the primary README and in the kernel-specific one :-)

**Pull request merged**
