### PR TITLE
Updates for kernel 4.0.5 and notes

### PR DESCRIPTION
**Pull request by cydergoth**
This pull request updates the patches for 4.0.5 and adds some notes from my experience.

Touchscreen doesn't work with this patch, so if you can spot what I've done wrong that would be helpful

### CODE REVIEW

**Comment by cydergoth** [comment]
Withdrawn as I've fixed the touchscreen issue! I'll file a new one shortly

**Comment by cydergoth** [comment]
Touchscreen depends on - and this is totally obscure - HID over I2c via one of the Haswell I2C drivers

**Comment by danielquinn** [comment]
Sweet!  Sorry I've been slow to respond on this, but I've been on vacation all this week.  When I get back home in another week I'll give this a shot and see about merging changes.  Just one question though: why 4.0.5 and not a 4.1.x variant?  Given that that's the latest out of `~arch`, I was just going to skip ahead to that when I found some time to fiddle with the kernel again.

**Comment by cydergoth** [comment]
I've just updated to 4.1.x, it was masked before.

Got pen, touch, wifi, type cover keys, type cover pad - except for weird
right click behavior - working

**Pull request closed without merging**
