### PR TITLE
kernel 4.0.2 config, including cleanups. 

### PR DESCRIPTION
**Pull request by fantasma13**
This is based on the 3.19.3 kernel, please apply these patches to 4.0.2 also, except the battery patch. I did not see any different behaviour when running 4.0.2 or 3.19.3, I guess it does not matter. 

The .config file is cleaned quite a bit, there is, however, the usb network device for my adapter included. You may modify it according to your needs.

### CODE REVIEW

**Comment by danielquinn** [comment]
Looks good. I'll give this a shot as soon as I can, but on 4.0.3, since [there appears to be a rather scary data corruption bug in 4.0.0 - 4.0.2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785672).  I'm glad that I've been putting off upgrading!

**Comment by fantasma13** [comment]
Hi,

I guess you don't have any clue regarding this issue?

https://forums.gentoo.org/viewtopic-t-1017776-highlight-gnome+bluetooth.html


Could I ask what kind of installation you have running, stable or not,
basic use flags, special packages? I'm really stuck, and reading you
have it working smoothly bugs me quite a bit.

Ingo

**Comment by danielquinn** [comment]
Well I'm not sure if it'll help, but here's what I've got currently:

```
# make.conf
CFLAGS="-march=core2 -O2 -pipe"
CXXFLAGS="${CFLAGS}"
CHOST="x86_64-pc-linux-gnu"
USE="connection-sharing bluetooth efiemu gnome-shell gtk gtk2 gtk3 jpeg laptop matroska mtp networkmanager ogm python sqlite theora threads v4l vim-syntax vpx vaapi webkit xpm -ldap -consolekit -qt -qt3 -qt4 -wxwidgets systemd"
CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"
ACCEPT_KEYWORDS="~amd64"
MAKEOPTS="-j5"
VIDEO_CARDS="intel v4l"
INPUT_DEVICES="evdev keyboard mouse synaptics elographics hyperpen mutouch penmount tslib"
LINGUAS="en_GB en"
EMERGE_DEFAULT_OPTS="--quiet-build"
DISTDIR="${PORTDIR}/distfiles"
PKGDIR="${PORTDIR}/packages"
GRUB_PLATFORMS="efi-64"
ABI_X86="64"

# package.use
net-libs/libproxy -webkit
net-wireless/wpa_supplicant -qt4
dev-vcs/git -gtk -perl
dev-db/postgresql server
media-gfx/darktable geo web-services
net-misc/tor transparent-proxy
sci-libs/gdal -java -mysql -perl -pdf
media-fonts/culmus ancient fancy
media-libs/mesa gles2

# Chromium
dev-libs/libxml2 icu

# Playing with fire
x11-wm/mutter -kms

# From London
gnome-base/gvfs cdda gdu archive fuse gphoto2 ios samba
dev-java/sun-jdk nsplugin
net-misc/curl static-libs -nss
app-shells/zsh doc examples
net-dns/bind dlz -threads
app-emulation/virtualbox qt4
sys-block/gparted ntfs
app-laptop/prey webcam
sys-devel/distcc -gtk gnome
net-fs/cifs-utils -acl
media-video/avidemux qt4
media-libs/avidemux-plugins lame twolame qt4
media-sound/rhythmbox python_targets_python3_3 html ipod visualizer
net-misc/networkmanager modemmanager
sys-libs/zlib minizip
media-libs/gd fontconfig
x11-base/xorg-server xvfb
app-misc/tracker firefox-bookmarks laptop networkmanager playlist thunderbird
app-misc/geoclue geonames
media-plugins/gst-plugins-meta ffmpeg
net-ftp/lftp -gnutls openssl
```

As for your particular problem, I'm honestly not sure :-(

**Comment by danielquinn** [comment]
Thanks to some help (and nudging) from cydergoth, I've updated this project to include support for 4.1.2.  Since this is a more recent kernel version, I'm closing this pull request as it is superceded by the latest update.

**Pull request closed without merging**
